apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-disks-operator
  namespace: {{ include "node-disks-manager.namespace" . }}
  labels:
    app.kubernetes.io/name: node-disks-operator
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: node-disks-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-disks-operator
    spec:
      serviceAccountName: node-disks-operator
      containers:
        - name: controller
          image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.controller.leaderElection }}
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: probes
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
          resources:
{{ toYaml .Values.controller.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: node-disks-operator-metrics
  namespace: {{ include "node-disks-manager.namespace" . }}
  labels:
    app.kubernetes.io/name: node-disks-operator
spec:
  selector:
    app.kubernetes.io/name: node-disks-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
