{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "node-disks-manager.namespace" . }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurity.enforce | quote }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurity.audit | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurity.warn | quote }}
{{- end }}
